### ISSUE TITLE
Add link to top of repo page

### ISSUE THREAD

**Issue by davelab6** [zhirzh/sugarizer-activity-moon#1]
Please add the link to https://zhirzh.github.io/sugarizer-activity-moon to the top of the repo page so it is easy to visit :)

<img width="659" alt="screen shot 2016-03-30 at 23 26 03" src="https://cloud.githubusercontent.com/assets/261579/14164593/d1386e08-f6ce-11e5-8521-e790c068faea.png">

**Comment by zhirzh** [comment]
Resolved. Thanks for pointing it out.

**Comment by zhirzh** [comment]
Resolved. Thanks for pointing it out.
