### ISSUE TITLE
How did you learn to write this project?

### ISSUE THREAD

**Issue by davelab6** [zhirzh/sugarizer-activity-moon#2]
I am curious, which resources did you rely on to learn how to write this project? :)

**Comment by zhirzh** [comment]
I am a GSoC aspirant and I started working on [Sugarizer Activity Set](https://wiki.sugarlabs.org/go/Summer_of_Code/2016). As a result, major code was ported from the [original source](https://github.com/godiard/moon-activity)

**Comment by davelab6** [comment]
I mean, which tutorials/docs did you use? :)
