### ISSUE TITLE
Date format not optimal in French

### ISSUE THREAD

**Issue by llaske** [zhirzh/sugarizer-activity-moon#5]
The date format use in french is not optimal (see below)

![capture](https://cloud.githubusercontent.com/assets/981841/14234742/04536922-f9eb-11e5-9fa5-0747ee46a3e4.PNG)

I guess it will be better to use the locale string format. Plus the string "heure d'été" has the wrong format.

**Comment by zhirzh** [comment]
fixed in https://github.com/zhirzh/sugarizer-activity-moon/pull/11/commits/34eb313bacdcbc505e4939f6202b2b1565a16813
