### ISSUE TITLE
The context of the activity is not saved in the Journal

### ISSUE THREAD

**Issue by llaske** [zhirzh/sugarizer-activity-moon#7]
On the Sugar activity, the "Grid" and "Hemisphere" position is saved in the Journal context. So when the activity is reopen, both are set at the previous value.

**Comment by zhirzh** [comment]
fixed in https://github.com/zhirzh/sugarizer-activity-moon/pull/11/commits/98c4e69a62b870b92cde1c552b51e67599c5080a
