### ISSUE TITLE
Tooltips on toolbar icons are not translated

### ISSUE THREAD

**Issue by llaske** [zhirzh/sugarizer-activity-moon#8]
Icons tooltips of the toolbar are not translated "Toggle Grid View", "Toggle Hemisphere View", "Save as image"

**Comment by llaske** [comment]
Nice to see you fixed it ! BTW it will be better to integrate my PR https://github.com/zhirzh/sugarizer-activity-moon/pull/3 first else you could have merging conflict

**Comment by zhirzh** [comment]
I merged the PR and thankfully, there were no conflicts.
