### ISSUE TITLE
Save as image icons should save image in the journal

### ISSUE THREAD

**Issue by llaske** [zhirzh/sugarizer-activity-moon#9]
The "Save as image" icons should save image in the journal, not download it.
It will allow to use the image in other activities.
Have a look of the Sugarizer "Record" activity to see how it could be done.

**Comment by zhirzh** [comment]
fixed in https://github.com/zhirzh/sugarizer-activity-moon/pull/11/commits/b99424026b73d3fc60756bd6b64a9d1a52b819a8
